### PR TITLE
Rework to add CooldownRestoration and ported Mana and Health fun to script

### LINKED ISSUE #5: Suggestion: improved cooldown reset
- **Improved cooldown reset**: when duel starts it resets the player cooldowns, when duel ends it restores the cooldowns that the player had before the duel

### PR DESCRIPTION
**Pull request by Gozzim**
- Added a function to save and restore Cooldowns
- Moved Health and Mana restoration to script

Closes #5

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
thanks @Gozzim !

@azerothcore/testers can anyone test this please?

**Comment by FrancescoBorzi** [comment]
@sedatyf can you please test this?

**Comment by Sedatyf** [comment]
> @Sedatyf can you please test this?

I can try yes. If I understand correctly, this is a mod right, so I have to install this mode and then use it in order to test it?

PS: is there some people who is ping when you do \@azerothcore/tester? I don't think I receive any notification with it

**Comment by Gozzim** [comment]
> I can try yes. If I understand correctly, this is a mod right, so I have to install this mode and then use it in order to test it?

Positive. Just clone it in the modules folder, recompile and adjust the config. You know the procedure.
Thanks alot :)

**Comment by FrancescoBorzi** [comment]
> > @Sedatyf can you please test this?
> 
> I can try yes. If I understand correctly, this is a mod right, so I have to install this mode and then use it in order to test it?
> 
> PS: is there some people who is ping when you do @azerothcore/tester? I don't think I receive any notification with it

yes and yes :)

thank you!

**Comment by Sedatyf** [comment]
Do you have any documentation about to give about mod?
You explained to me I had to put some folder on my project and compile it. So in this case I have to pull this project, put it in my azerothcore git folder, compile it, and test it, right?

**Comment by Sedatyf** [comment]
> Positive. Just clone it in the modules folder, recompile and adjust the config. You know the procedure.
> Thanks alot :)

Ah sorry, I didn't see that message. Ignore my last comment then. I'll check this out and I'll keep you updated

**Comment by Sedatyf** [comment]
Alright guys, here the result of my test.
It seems that cooldowns doesn't reset at the start of a duel. But, when you start a duel, your health and mana is full. And when duel ends, you retrieve your former heal/mana amount. Please see videos below for reference.

https://user-images.githubusercontent.com/59012307/116730862-4846b680-a9e9-11eb-9bdc-65c4f95d7f64.mp4

https://user-images.githubusercontent.com/59012307/116730872-4b41a700-a9e9-11eb-9a08-85eb0c4c73b7.mp4

Here is informations about my server. I cloned this repo in my module folder. I then pulled this PR. Finally I re-ran CMAKE and Build. Launched my server. And finally I had a message on my console which says module is loaded

image

My conf file ``duelreset.conf`` in my server file is like this
```conf
[worldserver]
#
#    DuelResetCooldowns
#        Description: Reset all cooldowns before duel starts and restore them when duel ends.
#        Default:     1  - (Enabled)
#                     0  - (Disabled)

DuelResetCooldowns = 1

#    DuelResetHealthMana
#        Description: Reset health and mana before duel starts and restore them when duel ends.
#        Default:     1  - (Enabled)
#                     0  - (Disabled)

DuelResetHealthMana = 1
```

**Comment by Gozzim** [comment]
> Alright guys, here the result of my test.
> It seems that cooldowns doesn't reset at the start of a duel. But, when you start a duel, your health and mana is full. And when duel ends, you retrieve your former heal/mana amount. Please see videos below for reference.

Yes, there is a reason for that. Cooldowns need to be at least 30 seconds old (so 30sec passed since the spell was used) and be at most 10min long in order to be reset.
This is the case to protect the system from being abused in open PvP for example.
So if you wait that time, it should be working as intended. I can also lower or remove that restriction if you find it unnecessary.

Also, it is important to note that when the cooldown is restored, the visualization (so greyed out icon) will start over, but only last the time saved before the duel started.

**Comment by Sedatyf** [comment]
Ah! I was not aware of that. Lemme try with a cooldowns of 30s or less then

>  I can also lower or remove that restriction if you find it unnecessary.

I can't answer that, it's @FrancescoBorzi call 😄

**Comment by Sedatyf** [comment]
Alright indeed, it's resetting cooldowns if they are under 30s and at the end, there is a short cooldown like you said ✔️ 

https://user-images.githubusercontent.com/59012307/116732920-b0969780-a9eb-11eb-90c4-908667d11c8c.mp4

Nice work @Gozzim!

**Comment by FrancescoBorzi** [comment]
> I can also lower or remove that restriction if you find it unnecessary.

I would make it configurable, but that can go in a separate PR :)

good job @Gozzim and @Sedatyf <3

**Pull request merged**
